# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WAGeoData
                                 A QGIS plugin
 The WA Geo Data plugin provides quick access to DMIRS publicly available map services.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Jesse Best
        email                : jessebest2@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtWidgets import QAction, QMenu
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.core import QgsNetworkAccessManager, Qgis
from functools import partial

from .resources import *
from .constants import PLUGIN_NAME, ABOUT_ICON, ABOUT_URL
from .helper import Helper
from .wms_layers import WMS_LAYERS
from .load_layer import *

import os

class WAGeoData:
    """QGIS Plugin Implementation."""
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        self.icon_path = os.path.join(
            os.path.dirname(__file__), ABOUT_ICON
        )

    def initGui(self):
        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName(PLUGIN_NAME)
        self.menu.setTitle(PLUGIN_NAME)

        self.menu_with_actions = []
        self.helpers = []
        self.services_remaining = len(WMS_LAYERS)

        if QgsNetworkAccessManager.instance().networkAccessible():
            for service in WMS_LAYERS:
                url = service["URL"]
                helper = Helper(QUrl(url + "?service=WMS&request=GetCapabilities&version=1.3.0"))
                helper.finished.connect(partial(self.create_menu,
                                service_name=service["Service"],
                                service_url=url))
                helper.error.connect(self.show_error)
                self.helpers.append(helper)
                helper.fetch()
        else:
            self.iface.messageBar().pushMessage("WA Geo Data:", "Failed to connect to network.", level=Qgis.Warning, duration=15)
            self.finish_menu()

    def create_menu(self, layers, service_name, service_url):
        group_menu = QMenu()
        group_menu.setTitle(service_name)
        
        for name in layers:
            action = QAction(name[0], self.iface.mainWindow())
            action.triggered.connect(partial(load_layer, layer=name, service_url=service_url, iface=self.iface))
            group_menu.addAction(action)
        
        self.menu.addMenu(group_menu)
        self.menu_with_actions.append(group_menu)

        if not hasattr(self, "_menu_added"):
            menu_bar = self.iface.mainWindow().menuBar()
            menu_bar.insertMenu(
                self.iface.firstRightStandardMenu().menuAction(), self.menu
            )
            self._menu_added = True
        
        self.services_remaining -= 1

        if self.services_remaining == 0:
            self.finish_menu()

    def finish_menu(self):
        if not hasattr(self, "_menu_added"):
            menu_bar = self.iface.mainWindow().menuBar()
            menu_bar.insertMenu(
                self.iface.firstRightStandardMenu().menuAction(), self.menu
            )
            self._menu_added = True

        self.create_about_menu()
        if not QgsNetworkAccessManager.instance().networkAccessible() or any(h.failed for h in self.helpers):
            self.create_reload_menu()

    def create_about_menu(self):
        self.about_menu = QAction(QIcon(self.icon_path), "About", self.iface.mainWindow())
        self.about_menu.triggered.connect(self.open_about_page)
        self.menu.addSeparator()
        self.menu.addAction(self.about_menu)

    def create_reload_menu(self):
        self.temp_menu = QAction(QIcon(self.icon_path),"Reload plugin", self.iface.mainWindow())
        self.temp_menu.triggered.connect(self.reload_menu)
        self.menu.addAction(self.temp_menu)
        
    def open_about_page(self):
        QDesktopServices.openUrl(QUrl(ABOUT_URL))

    def show_error(self, message):
        self.services_remaining -= 1
        self.iface.messageBar().pushMessage("WA Geo Data:", message, level=Qgis.Warning, duration=15)
        if self.services_remaining == 0:
            self.finish_menu()
        
    def unload(self):
        self.clear_menu()

    def reload_menu(self):
        self.clear_menu()       
        self.initGui()

    def clear_menu(self):
        for child in self.menu_with_actions:
            if child:
                child.deleteLater()
        if self.menu:
            self.menu.clear()
            self.menu.deleteLater()
        self.menu_with_actions = []
        self.helpers = []

        if hasattr(self, "_menu_added"):
            delattr(self, "_menu_added")